# Generated by Django 6.0.2 on 2026-02-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='city',
            field=models.CharField(default='مشهد', max_length=100, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='hall',
            name='price_per_hour',
            field=models.PositiveIntegerField(default=100000, verbose_name='قیمت هر ساعت (تومان)'),
        ),
        migrations.AddField(
            model_name='hall',
            name='rating',
            field=models.FloatField(default=5.0, verbose_name='امتیاز'),
        ),
        migrations.AddField(
            model_name='hall',
            name='sport',
            field=models.CharField(default='فوتبال', max_length=100, verbose_name='ورزش'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='amenities',
            field=models.TextField(help_text='امکانات را با کاما (,) جدا کنید. مثال: دوش, بوفه, پارکینگ', verbose_name='امکانات'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='location',
            field=models.CharField(max_length=255, verbose_name='آدرس دقیق'),
        ),
    ]
