# Generated by Django 6.0.2 on 2026-02-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hall_city_hall_price_per_hour_hall_rating_hall_sport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'کاربر عادی'), ('venue-manager', 'مدیر سالن')], default='user', max_length=20, verbose_name='نقش کاربر'),
        ),
    ]
