# Generated by Django 6.0.2 on 2026-02-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='description',
            field=models.TextField(blank=True, default='یک سالن ورزشی مجهز با امکانات کامل.', verbose_name='توضیحات'),
        ),
    ]
