# Generated by Django 6.0.2 on 2026-02-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_hall_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='priority',
            field=models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'فوری')], default='medium', max_length=20, verbose_name='اولویت'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='type',
            field=models.CharField(choices=[('bug', 'خطا'), ('payment', 'پرداخت'), ('venue', 'سالن ها'), ('account', 'حساب کاربری'), ('other', 'سایر')], default='Bug', max_length=20, verbose_name='نوع پیام'),
        ),
    ]
