# Generated by Django 6.0.2 on 2026-02-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contactmessage_priority_contactmessage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'کاربر عادی'), ('venue-manager', 'مدیر سالن'), ('sys-admin', 'مدیر سیستم')], default='user', max_length=20, verbose_name='نقش کاربر'),
        ),
    ]
