# Generated by Django 6.0.2 on 2026-02-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='capacity',
            field=models.PositiveIntegerField(default=10, verbose_name='ظرفیت نفرات'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='location',
            field=models.CharField(default='آدرس ثبت نشده', max_length=255, verbose_name='آدرس دقیق'),
        ),
    ]
